### ISSUE TITLE
Can support be added for "Ion Fury"?

### ISSUE THREAD

**Issue by duduke** [Rinnegatamante/EDuke32-Vita#5]
"Ion Fury" http://www.ionfury.com/ relies on a newer EDUKE32.
Can a newer version of eDuke32 ported to the VITA?

**Comment by Rinnegatamante** [comment]
Can? Yes.
Gonna work on it personally? Nope, i hugely dislike both EDuke32 codebase and Build engine codebase in general.
EDuke32 codebase doesn't take into account when a system has long/int != int32_t causing a storm of errors at every single file you compile (trying to compile latest master of EDuke32 with arm-vita-eabi would cause you to get something like 20k+ compiling errors).
I've already had enough headaches to actually adapt this mess three times (EDuke32, NRedneck and NBlood) and not willing to go again through all this for a forth time.

**Comment by duduke** [comment]
Got it, thanks.

**Comment by Magicrafter13** [comment]
Probably should have looked here before I spent an hour trying to run it lol
